apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  # labels:
  #   olm.owner: seldon-operator.v1.7.0
  #   olm.owner.kind: ClusterServiceVersion
  #   operators.coreos.com/seldon-operator-certified.ml-workshop: ""
  name: seldon-operator.v1.7.0-seldon-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: seldon-operator.v1.7.0-seldon-manager-role
subjects:
- kind: ServiceAccount
  name: seldon-manager
  namespace: ml-workshop
