apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base

resources:
  - jupyterhub-ingress.yaml
  
patchesStrategicMerge:
  - jupyterhub-db-dc.yaml


commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: jupyterhub