# apiVersion: apps.openshift.io/v1
# kind: DeploymentConfig
apiVersion: apps/v1
kind: StatefulSet

metadata:
  labels:
    app: jupyterhub
  name: jupyterhub-db
spec:
  serviceName: jupyterhub-db
  replicas: 1
  selector:
    app: jupyterhub
    deploymentconfig: jupyterhub-db
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jupyterhub
        deploymentconfig: jupyterhub-db
        component.opendatahub.io/name: jupyterhub
        opendatahub.io/component: 'true'
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: quay.io/ml-aml-workshop/postgresql-96
        env:
        - name: POSTGRESQL_USER
          value: jupyterhub
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(jupyterhub_secret)
              key: POSTGRESQL_PASSWORD
        - name: POSTGRESQL_DATABASE
          value: jupyterhub
        livenessProbe:
          tcpSocket:
            port: 5432
        name: postgresql
        ports:
        - containerPort: 5432
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -i
            - -c
            - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c
              'SELECT 1'
        resources:
          limits:
            memory: 1Gi
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: jupyterhub-db
      - configMap:
          defaultMode: 420
          name: jupyterhub-cfg
        name: config
  triggers:
  - type: ConfigChange
