apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: jupyterhub
  label:
    app: jupyterhub
data:
  POSTGRESQL_PASSWORD: c2VjcmV0cGFzc3dvcmQ= # "secretpassword"
  PROMETHEUS_API_TOKEN: ZDE2ZGMwZDFhY2YyMTMxMzY3ZmZmM2E3MjQzNmZhOTFlZTEzYjcxODgwY2JhZjZlMjMxMWZlNmZkZDU2NTM4NA== # "openssl rand -hex 32 | base64"
  CONFIGPROXY_AUTH_TOKEN: M2MxNTVjZTczNDQ1NzNhOTRiMjA5YmM4NzVjMmE3NDliN2ZhZGVhMDdlOTQyMGFhYzQyZGJjZjYyYWIwODMxZQ== # "openssl rand -hex 32 | base64"
  JPY_COOKIE_SECRET: MWVmNzA2MjEzMmEyNmNlMDZkZmU3MzY2NWZkYTE2YmJkZTZiNDAyNTZjYTQ3MjkzZmMyYjJiNjY3MGFjODMyMw== # "openssl rand -hex 32 | base64"
  JUPYTERHUB_CRYPT_KEY: YTEyMjIwMmQwZTM5YjNiY2U0MTExNDVkZDcwNTc2ZmFkMzU3OWZhYjAwNjE1ZjEyYTExYjcyNjBiYmY5Nzk1YQ== # "openssl rand -hex 32 | base64"
