kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jupyterhub-cluster
subjects:
  - kind: ServiceAccount
    name: jupyterhub-hub
    namespace: $(namespace)
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jupyterhub-cluster
