apiVersion: v1
kind: LimitRange
metadata:
  name: ml-workshop-limit-range
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 500m
    defaultRequest:
      memory: 256Mi
      cpu: 50m
    type: Container