apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - secrets.yaml
  - service.yaml
  - service-accounts.yaml
  - route.yaml
  - default-role-binding.yaml

commonLabels:
  opendatahub.io/component: "false"
  component.opendatahub.io/name: "airflow2"
