apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/thoth-station/s2i-lab-elyra"
    opendatahub.io/notebook-image-name: "Elyra Notebook Image with Spark"
    opendatahub.io/notebook-image-desc: "Jupyter notebook image with Elyra-AI installed"
  name: s2i-lab-elyra-spark
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/imported-from: quay.io/thoth-station/s2i-lab-elyra
    from:
      kind: DockerImage
      name: quay.io/ml-aml-workshop/elyra-spark:0.0.4
    name: "0.0.4"
    referencePolicy:
      type: Source
