apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sparkapplications.radanalytics.io
spec:
  conversion:
    strategy: None
  group: radanalytics.io
  names:
    kind: SparkApplication
    listKind: SparkApplicationList
    plural: sparkapplications
    singular: sparkapplication
  preserveUnknownFields: true
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}